x-lagoon-route: &default-url
  http://${COMPOSE_PROJECT_NAME:-umami}.docker.amazee.io

x-environment: &default-environment
  UMAMI_VERSION: 2.15.1
  HASH_SALT: replace-me-with-a-random-string
  DB_DATABASE: lagoon
  DB_USERNAME: lagoon
  DB_PASSWORD: lagoon
  DB_HOST: db
  DB_PORT: 3306


services:
  nginx:
    container_name: hugo
    build:
      context: .
      dockerfile: lagoon/nginx.Dockerfile
      args:
        HUGO_BASEURL: ${HUGO_BASEURL}
    labels:
      lagoon.type: nginx
      lagoon.service.usecomposeports: true
    ports:
      - "1313:1313"
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
      LAGOON_ROUTE: http://hugo.docker.amazee.io
      LAGOON_LOCALDEV_HTTP_PORT: "1313"

  umami:
    container_name: umami
    build:
      context: .
      dockerfile: lagoon/umami.Dockerfile
      args:
        UMAMI_VERSION: mysql-v2.15.1
    ports:
      - 3000
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
      LAGOON_ROUTE: http://umami.docker.amazee.io
      LAGOON_LOCALDEV_HTTP_PORT: 3000
    labels:
      lagoon.type: node
    depends_on:
      - db

  db:
    image: uselagoon/mysql-8.0:latest
    restart: always
    labels:
      lagoon.type: mariadb
      lagoon.image: uselagoon/mysql-8.0:latest
    ports:
      - "3306"


networks:
  amazeeio-network:
    external: true
