services:
  nginx:
    container_name: hugo
    build:
      context: .
      dockerfile: lagoon/nginx.Dockerfile
      args:
        HUGO_BASEURL: ${HUGO_BASEURL}
    labels:
      lagoon.type: nginx
      lagoon.service.usecomposeports: true
    ports:
      - "1313:1313"
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
      LAGOON_ROUTE: http://hugo.docker.amazee.io
      LAGOON_LOCALDEV_HTTP_PORT: "1313"

networks:
  amazeeio-network:
    external: true
